class Keploy < Formula
  desc "Testing Toolkit creates test-cases and data mocks from API calls, DB queries"
  homepage "https://keploy.io"
  url "https://github.com/keploy/keploy/archive/refs/tags/v3.5.29.tar.gz"
  sha256 "834bfa9b30fb88f04f141201501875f157abe74c0f5d6823e3d2bee1b1fec326"
  license "Apache-2.0"
  head "https://github.com/keploy/keploy.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_tahoe:   "3c1d68bafab52bf1d68693df58a70d41fb02a8d4b606e0ed5d25b75a979a92a8"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "3c1d68bafab52bf1d68693df58a70d41fb02a8d4b606e0ed5d25b75a979a92a8"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "3c1d68bafab52bf1d68693df58a70d41fb02a8d4b606e0ed5d25b75a979a92a8"
    sha256 cellar: :any_skip_relocation, sonoma:        "47c6d3f8d5fec60f8a992f5aa6daa151f11eece522680746bf3989859268f840"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "5bbdc9ea44bc85854bc2bb5dac82c975788aa150956bfe47a7337ef05578e43b"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "ce6ec3cee8e0af8ce73a26b8b0ec7325e9ae239f6eb7bda8f6268022be8c8a21"
  end

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w -X main.version=#{version}")
  end

  test do
    system bin/"keploy", "config", "--generate", "--path", testpath
    assert_match "# Generated by Keploy", (testpath/"keploy.yml").read

    assert_match version.to_s, shell_output("#{bin}/keploy --version")
  end
end
