class Keploy < Formula
  desc "Testing Toolkit creates test-cases and data mocks from API calls, DB queries"
  homepage "https://keploy.io"
  url "https://github.com/keploy/keploy/archive/refs/tags/v3.5.24.tar.gz"
  sha256 "4bf5be867aab859d7a75086a93c96b6c4502921af2fe5c80f51e806ef6561065"
  license "Apache-2.0"
  head "https://github.com/keploy/keploy.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_tahoe:   "6d902d47e54e7c670a31b2ef91e7cd979c5d9ef730c92c99c78afd076add1b1d"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "6d902d47e54e7c670a31b2ef91e7cd979c5d9ef730c92c99c78afd076add1b1d"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "6d902d47e54e7c670a31b2ef91e7cd979c5d9ef730c92c99c78afd076add1b1d"
    sha256 cellar: :any_skip_relocation, sonoma:        "ec3a3bc2d8bb0850ebf97088dddeb27a469b505272bf5cf32d28f865570d06fe"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "d2410c37add37f03a5a0570d47f8898095c4c4f4a2c19f8b31da6411e78dc832"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "3bf1da1b0bea9a98bd22b99e4bc48f681ab003e85a916ac34a511b49ae16541f"
  end

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w -X main.version=#{version}")
  end

  test do
    system bin/"keploy", "config", "--generate", "--path", testpath
    assert_match "# Generated by Keploy", (testpath/"keploy.yml").read

    assert_match version.to_s, shell_output("#{bin}/keploy --version")
  end
end
