class Uv < Formula
  desc "Extremely fast Python package installer and resolver, written in Rust"
  homepage "https://docs.astral.sh/uv/"
  url "https://github.com/astral-sh/uv/archive/refs/tags/0.11.10.tar.gz"
  sha256 "9880a22700988cfc9cfd54f575180672a43449e5621f99941494548a99309388"
  license any_of: ["Apache-2.0", "MIT"]
  compatibility_version 1
  head "https://github.com/astral-sh/uv.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_tahoe:   "527a0c73e8fe3f756e386a0c0320e75a1908f7fcc4469c586062db9cf51ce0e5"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "4ae7f7d72cbbdd376d0bf9da489fb07eeb3a52da8bb63430ea626599560720fc"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "ace69c74dd61b09f01c3fe416fc99d336c93da48596be3634676841e326ac3f3"
    sha256 cellar: :any_skip_relocation, sonoma:        "6cc6272e065a59351a5b22a007572c54b2885982e0f48f139a7ef13dd8dae3e3"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "d649e38e8817d8d0654d4e779a588de6b441696467d56162aa0eca1c0607292f"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "04c995e6cca920ca6f92165bec89f33ae97e82b76fdfd0a8e7d4a1e35bd3f526"
  end

  depends_on "pkgconf" => :build
  depends_on "rust" => :build

  uses_from_macos "python" => :test
  uses_from_macos "bzip2"
  uses_from_macos "xz"

  def install
    ENV["UV_COMMIT_HASH"] = ENV["UV_COMMIT_SHORT_HASH"] = tap.user
    ENV["UV_COMMIT_DATE"] = time.strftime("%F")
    # See: https://github.com/astral-sh/uv/issues/15401
    ENV["JEMALLOC_SYS_WITH_LG_PAGE"] = "16" if Hardware::CPU.arm? && OS.linux?
    system "cargo", "install", *std_cargo_args(path: "crates/uv")
    generate_completions_from_executable(bin/"uv", "generate-shell-completion")
    generate_completions_from_executable(bin/"uvx", "--generate-shell-completion")
  end

  test do
    (testpath/"requirements.in").write <<~REQUIREMENTS
      requests
    REQUIREMENTS

    compiled = shell_output("#{bin}/uv pip compile -q requirements.in")
    assert_match "This file was autogenerated by uv", compiled
    assert_match "# via requests", compiled

    assert_match "ruff 0.5.1", shell_output("#{bin}/uvx -q ruff@0.5.1 --version")
  end
end
